services:
  - type: web
    name: attendance-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    env:
      MONGO_URI: "your-mongodb-uri"
      PORT: "10000"

  - type: web
    name: attendance-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
